export default {
  rules: {
    'arrow-body-style': 0,
    'camelcase': [1, {
      allow: ['^UNSAFE_'],
      properties: 'never',
    }],
    'capitalized-comments': 0,
    'class-methods-use-this': 0,
    'consistent-return': 1,
    'curly': [2, 'all'],
    'default-case': 2,
    'default-param-last': 0,
    'dot-notation': [1, {
      allowKeywords: true,
    }],
    'eqeqeq': 2,
    'func-names': 0,
    'max-classes-per-file': 0,
    'max-lines-per-function': 0,
    'new-cap': [2, { newIsCap: true, capIsNew: false }],
    'no-alert': 1,
    'no-array-constructor': 2,
    'no-caller': 2,
    'no-cond-assign': [2, 'except-parens'],
    'no-const-assign': 2,
    'no-constant-binary-expression': 2,
    'no-constructor-return': 0,
    'no-console': [1, { allow: ['warn', 'error'] }],
    'no-continue': 0,
    'no-else-return': 0,
    'no-extra-boolean-cast': 0,
    'no-lone-blocks': 0,
    'no-param-reassign': 0,
    'no-plusplus': 0,
    'no-prototype-builtins': 1,
    'no-restricted-properties': 0,
    'no-restricted-syntax': 0,
    'no-return-await': 0,
    'no-shadow': 0,
    'no-underscore-dangle': 0,
    'no-unused-expressions': [2, {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: true,
    }],
    'no-unused-vars': [1, {
      vars: 'local',
      args: 'none',
      varsIgnorePattern: '^_',
      argsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_',
    }],
    'no-use-before-define': 0,
    'no-useless-assignment': 0,
    'no-useless-backreference': 2,
    'no-useless-call': 0,
    'no-useless-catch': 2,
    'no-useless-computed-key': 0,
    'no-useless-concat': 0,
    'no-useless-constructor': 0,
    'no-useless-escape': 1,
    'no-useless-rename': 0,
    'no-useless-return': 0,
    'no-var': 2,
    'object-shorthand': 0,
    'one-var': 0,
    'prefer-const': 1,
    'prefer-destructuring': 0,
    'prefer-object-has-own': 0,
    'prefer-object-spread': 0,
    'prefer-promise-reject-errors': [1, {
      allowEmptyReject: true,
    }],
    'prefer-regex-literals': 0,
    'prefer-spread': 0,
    'prefer-template': 0,
    'require-await': 1,
    'vars-on-top': 0,
  },
};
