// https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/master/docs/rules
export default {
  rules: {
    'jsx-a11y/alt-text': [2, {
      elements: ['img', 'object', 'area', 'input[type="image"]'],
      img: [],
      object: [],
      area: [],
      'input[type="image"]': [],
    }],
    'jsx-a11y/anchor-has-content': [2, { components: [] }],
    'jsx-a11y/anchor-is-valid': [2, {
      components: ['Link'],
      specialLink: ['to'],
      aspects: ['noHref', 'invalidHref', 'preferButton'],
    }],
    'jsx-a11y/aria-activedescendant-has-tabindex': 2,
    'jsx-a11y/aria-props': 2,
    'jsx-a11y/aria-proptypes': 2,
    'jsx-a11y/aria-role': [2, { ignoreNonDom: false }],
    'jsx-a11y/aria-unsupported-elements': 2,
    'jsx-a11y/click-events-have-key-events': 1,
    'jsx-a11y/control-has-associated-label': 1,
    'jsx-a11y/heading-has-content': [2, { components: [''] }],
    'jsx-a11y/html-has-lang': 2,
    'jsx-a11y/iframe-has-title': 2,
    'jsx-a11y/img-redundant-alt': 2,
    'jsx-a11y/interactive-supports-focus': 1,
    'jsx-a11y/label-has-associated-control': 0,
    'jsx-a11y/lang': 2,
    'jsx-a11y/media-has-caption': [1, {
      audio: [],
      video: [],
      track: [],
    }],
    'jsx-a11y/mouse-events-have-key-events': 1,
    'jsx-a11y/no-access-key': 2,
    'jsx-a11y/no-autofocus': [1, { ignoreNonDOM: true }],
    'jsx-a11y/no-distracting-elements': [2, {
      elements: ['marquee', 'blink'],
    }],
    'jsx-a11y/no-interactive-element-to-noninteractive-role': [2, {
      tr: ['none', 'presentation'],
    }],
    'jsx-a11y/no-noninteractive-element-interactions': [1, {
      handlers: [
        'onClick',
        'onMouseDown',
        'onMouseUp',
        'onKeyPress',
        'onKeyDown',
        'onKeyUp',
      ],
    }],
    'jsx-a11y/no-noninteractive-element-to-interactive-role': [2, {
      ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
      ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
      li: ['menuitem', 'option', 'row', 'tab', 'treeitem'],
      table: ['grid'],
      td: ['gridcell'],
    }],
    'jsx-a11y/no-noninteractive-tabindex': [1, {
      tags: [],
      roles: ['tabpanel'],
    }],
    'jsx-a11y/no-redundant-roles': 1,
    'jsx-a11y/no-static-element-interactions': [1, {
      handlers: [
        'onClick',
        'onMouseDown',
        'onMouseUp',
        'onKeyPress',
        'onKeyDown',
        'onKeyUp',
      ],
    }],
    'jsx-a11y/role-has-required-aria-props': 2,
    'jsx-a11y/role-supports-aria-props': 2,
    'jsx-a11y/scope': 2,
    'jsx-a11y/tabindex-no-positive': 2,
  },
};
