export default {
  rules: {
    '@stylistic/array-bracket-newline': 0,
    '@stylistic/array-bracket-spacing': [2, 'never'],
    '@stylistic/array-element-newline': 0,
    '@stylistic/arrow-parens': [2, 'as-needed', { 'requireForBlockBody': true }],
    '@stylistic/arrow-spacing': [2, { 'after': true, 'before': true }],
    '@stylistic/block-spacing': [2, 'always'],
    '@stylistic/brace-style': [2, 'stroustrup', { 'allowSingleLine': true }],
    '@stylistic/comma-dangle': [2, 'always-multiline'],
    '@stylistic/comma-spacing': [2, { 'after': true, 'before': false }],
    '@stylistic/comma-style': [2, 'last'],
    '@stylistic/computed-property-spacing': [2, 'never', { 'enforceForClassMembers': true }],
    '@stylistic/curly-newline': 0,
    '@stylistic/dot-location': [2, 'property'],
    '@stylistic/eol-last': 2,
    '@stylistic/exp-jsx-props-style': 0,
    '@stylistic/exp-list-style': 0,
    '@stylistic/function-call-argument-newline': 0,
    '@stylistic/function-call-spacing': 0,
    '@stylistic/function-paren-newline': 0,
    '@stylistic/generator-star-spacing': [2, { 'after': true, 'before': false }],
    '@stylistic/implicit-arrow-linebreak': 0,
    '@stylistic/indent': [2, 2, {
      'ArrayExpression': 1,
      'CallExpression': { 'arguments': 1 },
      'flatTernaryExpressions': false,
      'FunctionDeclaration': { 'body': 1, 'parameters': 1, 'returnType': 1 },
      'FunctionExpression': { 'body': 1, 'parameters': 1, 'returnType': 1 },
      'ignoreComments': false,
      'ignoredNodes': ['TSUnionType', 'TSIntersectionType'],
      'ImportDeclaration': 1,
      'MemberExpression': 1,
      'ObjectExpression': 1,
      'offsetTernaryExpressions': true,
      'outerIIFEBody': 1,
      'SwitchCase': 1,
      'tabLength': 2,
      'VariableDeclarator': 1,
    }],
    '@stylistic/indent-binary-ops': [2, 2],
    '@stylistic/jsx-child-element-spacing': 0,
    '@stylistic/jsx-closing-bracket-location': 2,
    '@stylistic/jsx-closing-tag-location': 2,
    '@stylistic/jsx-curly-brace-presence': [2, { 'propElementValues': 'always' }],
    '@stylistic/jsx-curly-newline': 2,
    '@stylistic/jsx-curly-spacing': [2, 'never'],
    '@stylistic/jsx-equals-spacing': 2,
    '@stylistic/jsx-first-prop-new-line': 2,
    '@stylistic/jsx-function-call-newline': [2, 'multiline'],
    '@stylistic/jsx-indent': 0,
    '@stylistic/jsx-indent-props': [2, 2],
    '@stylistic/jsx-max-props-per-line': [2, { 'maximum': 1, 'when': 'multiline' }],
    '@stylistic/jsx-newline': 0,
    '@stylistic/jsx-one-expression-per-line': [2, { 'allow': 'single-child' }],
    '@stylistic/jsx-pascal-case': 0,
    '@stylistic/jsx-props-no-multi-spaces': 0,
    '@stylistic/jsx-quotes': 2,
    '@stylistic/jsx-self-closing-comp': 0,
    '@stylistic/jsx-sort-props': 0,
    '@stylistic/jsx-tag-spacing': [2, {
      'afterOpening': 'never',
      'beforeClosing': 'never',
      'beforeSelfClosing': 'always',
      'closingSlash': 'never',
    }],
    '@stylistic/jsx-wrap-multilines': [2, {
      'arrow': 'parens-new-line',
      'assignment': 'parens-new-line',
      'condition': 'parens-new-line',
      'declaration': 'parens-new-line',
      'logical': 'parens-new-line',
      'prop': 'parens-new-line',
      'propertyValue': 'parens-new-line',
      'return': 'parens-new-line',
    }],
    '@stylistic/key-spacing': [2, {
      'afterColon': true,
      'beforeColon': false,
    }],
    '@stylistic/keyword-spacing': [2, { 'after': true, 'before': true }],
    '@stylistic/line-comment-position': 0,
    '@stylistic/linebreak-style': 0,
    '@stylistic/lines-around-comment': 0,
    '@stylistic/lines-between-class-members': [2, 'always', { 'exceptAfterSingleLine': true }],
    '@stylistic/max-len': 0,
    '@stylistic/max-statements-per-line': [2, { 'max': 1 }],
    '@stylistic/member-delimiter-style': [2, {
      'multiline': { 'delimiter': 'none', 'requireLast': false },
      'multilineDetection': 'brackets',
      'overrides': {
        'interface': {
          'multiline': { 'delimiter': 'none', 'requireLast': false },
        },
      },
      'singleline': { 'delimiter': 'comma' },
    }],
    '@stylistic/multiline-comment-style': 0,
    '@stylistic/multiline-ternary': [2, 'always-multiline'],
    '@stylistic/new-parens': 2,
    '@stylistic/newline-per-chained-call': 0,
    '@stylistic/no-confusing-arrow': 0,
    '@stylistic/no-extra-parens': [2, 'functions'],
    '@stylistic/no-extra-semi': 0,
    '@stylistic/no-floating-decimal': 2,
    '@stylistic/no-mixed-operators': [2, {
      'allowSamePrecedence': true,
      'groups': [
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
    }],
    '@stylistic/no-mixed-spaces-and-tabs': 2,
    '@stylistic/no-multi-spaces': 2,
    '@stylistic/no-multiple-empty-lines': [2, { 'max': 1, 'maxBOF': 0, 'maxEOF': 0 }],
    '@stylistic/no-tabs': 2,
    '@stylistic/no-trailing-spaces': 2,
    '@stylistic/no-whitespace-before-property': 2,
    '@stylistic/nonblock-statement-body-position': 0,
    '@stylistic/object-curly-newline': 0,
    '@stylistic/object-curly-spacing': [2, 'always'],
    '@stylistic/object-property-newline': 0,
    '@stylistic/one-var-declaration-per-line': 0,
    '@stylistic/operator-linebreak': [2, 'before'],
    '@stylistic/padded-blocks': [2, { 'blocks': 'never', 'classes': 'never', 'switches': 'never' }],
    '@stylistic/padding-line-between-statements': 0,
    '@stylistic/quote-props': [2, 'consistent-as-needed'],
    '@stylistic/quotes': [2, 'single', { 'allowTemplateLiterals': 'always', 'avoidEscape': false }],
    '@stylistic/rest-spread-spacing': [2, 'never'],
    '@stylistic/semi': [2, 'never'],
    '@stylistic/semi-spacing': [2, { 'after': true, 'before': false }],
    '@stylistic/semi-style': 0,
    '@stylistic/space-before-blocks': [2, 'always'],
    '@stylistic/space-before-function-paren': [2, { 'anonymous': 'always', 'asyncArrow': 'always', 'named': 'never' }],
    '@stylistic/space-in-parens': [2, 'never'],
    '@stylistic/space-infix-ops': 2,
    '@stylistic/space-unary-ops': [2, { 'nonwords': false, 'words': true }],
    '@stylistic/spaced-comment': [2, 'always', {
      'block': { 'balanced': true, 'exceptions': ['*'], 'markers': ['!'] },
      'line': { 'exceptions': ['/', '#'], 'markers': ['/'] },
    }],
    '@stylistic/switch-colon-spacing': 0,
    '@stylistic/template-curly-spacing': 2,
    '@stylistic/template-tag-spacing': [2, 'never'],
    '@stylistic/type-annotation-spacing': [2, {}],
    '@stylistic/type-generic-spacing': 2,
    '@stylistic/type-named-tuple-spacing': 2,
    '@stylistic/wrap-iife': [2, 'any', { 'functionPrototypeMethods': true }],
    '@stylistic/wrap-regex': 0,
    '@stylistic/yield-star-spacing': [2, { 'after': true, 'before': false }],
  }
};
